# Per-image numbers for "if <photographer> edited this photo": a scene signature and the finished
# tone/colour of every published image. Same formulas as engine/style.js (signature) and
# engine/finish.js (targets). Writes engine/style-data.js.
# usage: python3 tools/style_records.py cvatik=scratch/pub/cvatik xenie=scratch/pub/xenie ...
import sys, json, glob, numpy as np
from PIL import Image
sys.path.insert(0, 'tools')
from measure_published import lab

def records(folder):
    out, seen = [], set()
    for f in sorted(glob.glob(folder + '/*')):
        try:
            im = Image.open(f).convert('RGB')
        except Exception:
            continue
        t = tuple((np.asarray(im.convert('L').resize((8, 8))) // 16).flatten())
        if t in seen: continue
        seen.add(t)
        s = min(1, 512 / max(im.size))
        im = im.resize((max(1, round(im.width * s)), max(1, round(im.height * s))), Image.BILINEAR)
        a = np.asarray(im).astype(np.float64); H, W = a.shape[:2]
        if W < 150 or H < 150: continue
        Lab = lab(a); L, A, B = Lab[..., 0], Lab[..., 1], Lab[..., 2]
        C = np.hypot(A, B); h = np.degrees(np.arctan2(B, A)) % 360; n = L.size
        col = C >= 10
        sec = lambda lo, hi: float(((h >= lo) & (h < hi) & col).sum() / n)
        warm, yellow, green, blue = sec(15, 75), sec(75, 110), sec(110, 180), sec(180, 300)
        magenta = float((col & ((h >= 300) | (h < 15))).sum() / n)
        top = max(1, int(H * 0.3))
        skin = float(((h > 25) & (h < 70) & (C > 8) & (C < 45) & (L > 30) & (L < 85)).sum() / n)
        sig = [np.percentile(L, 50, method='lower'), np.percentile(L, 90, method='lower') - np.percentile(L, 10, method='lower'),
               warm, yellow, green, blue, magenta, float((C < 6).sum() / n), L[:top].mean() - L.mean(), skin]
        band = lambda m: [float(A[m].mean()), float(B[m].mean())] if m.sum() > n * 0.03 else [None, None]
        yy, xx = np.mgrid[0:H, 0:W]; rr = np.hypot(xx / W - .5, yy / H - .5)
        bw = bool(C.mean() < 3)
        tg = [np.percentile(L, 1), np.percentile(L, 99), C.mean(), *band(L < 30), *band((L >= 30) & (L < 70)), *band(L >= 70),
              L[rr < .2].mean() - L[rr > .6].mean(), 1 if bw else 0]
        out.append([None if v is None else round(float(v), 3 if abs(float(v)) < 1 else 1) for v in sig + tg])
    return out

if __name__ == '__main__':
    data = {}
    for arg in sys.argv[1:]:
        key, folder = arg.split('=')
        data[key] = {'rows': records(folder)}
        print(key, len(data[key]['rows']), 'images', file=sys.stderr)
    js = ('// Generated by tools/style_records.py from each photographer\'s published portfolio (measured numbers only,\n'
          '// no images). Row = SIG_FIELDS then TARGET_FIELDS from engine/style.js.\n'
          'export const STYLE_DATA = ' + json.dumps(data, separators=(',', ':')) + ';\n')
    open('engine/style-data.js', 'w').write(js)
